name: Build Angular
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
        - uses: actions/checkout@v1

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install NPM
          run:  npm install

        - name: Update Npm
          run:  npm update

        - name: NpM angular CLI
          run: npm install -g @angular/cli@8.3.28

        - name: prepare to move
          run: mkdir Move ; mv ./[a-z]* ./Move

        - name: clone pia repo
          run: git clone https://github.com/LINCnil/pia.git

          # git clone https://github.com/atnos/pia.git
          # your_username
          # your_token

        - name: create library
          run: cd pia ; ng generate library pia-i18n

        - name: clear directory
          run: rm ./pia/projects/pia-i18n/* -R

        - name: move files
          run: mv ./Move ./pia/projects/pia-i18n

        - name: build library
          run: cd pia ; ng build pia-i18n
