name: Build Angular
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
        - uses: actions/checkout@v1

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install NPM
          run:  npm install
        
        - name: Update Npm
          run:  npm update
        
        - name: NpM angular CLI 
          run: npm install -g @angular/cli
        
        - name: create app
          run: ng new My-app
        
        - name: create directory projects
          run: mkdir ./My-app/projects

        - name: create directory pia-i18n
          run: mkdir ./My-app/projects/pia-i18n

        - name: move files
          run: mv ./[a-z]* ./My-app/pia-i18n
        
        - name: build library
          run:  cd My-app ; ng build pia-i18n