name: Build Angular
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
        - uses: actions/checkout@v1
          # with:
          #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Install NPM
          run:  npm install

        - name: Update Npm
          run:  npm update

        - name: NpM angular CLI
          run: npm install -g @angular/cli@8.3.28

        - name: prepare to move
          run: mkdir Move ; mv ./[a-z]* ./Move

        - name: create app and prepare with dependancies
          run: ng new pia; cd pia; npm install @ngx-translate/core; npm install @ngx-translate/http-loader;
          # "@ngx-translate/core": "^13.0.0",
          # "@ngx-translate/http-loader": "^6.0.0",

        #  cd pia; rm package.json; rm -rf node_modules; cp ../Move/package-for-app.json package.json; npm install

        # - name: CREATE APP ANGULAR
        #   run: git clone https://github.com/LINCnil/pia.git

          # git clone https://github.com/atnos/pia.git
          # your_username
          # your_token

        - name: prepare library
          run: cd pia ; ng generate library pia-i18n ; rm ./projects/pia-i18n/* -R

        - name: go to Move folder, get files and move them to pia-i18n
          run: mv ./Move/[a-z]* ./pia/projects/pia-i18n

        - name: return pia projet and build library
          run: cd ./pia ; ng build pia-i18n

        - name: create tgz file
          run: cd ./pia/dist/pia-i18n ; npm pack

        - name: publish library
          run: cd ./pia ; npm publish dist/pia-i18n/pia-i18n-0.0.1.tgz --access public
